#!/bin/bash

set -e

this_ip="$1"; shift
this_machine="$1"; shift
consul_args="$@"

etcdctl="docker run --net=host --rm cap10morgan/etcdctl:0.4.6"
conntrack="docker run --net=host --privileged --rm cap10morgan/conntrack"

function leave-cluster {
  ${etcdctl} rm /consul.io/bootstrap/machines/${this_machine}
  consul leave
  # work around a Docker / Consul interaction bug that makes quickly-restarted containers not sync
  ${conntrack} -F
}

trap leave-cluster EXIT

${etcdctl} ls /consul.io/bootstrap/machines || ${etcdctl} mkdir /consul.io/bootstrap/machines

nodes=( $(${etcdctl} ls /consul.io/bootstrap/machines) )

if [[ ${#nodes[@]} > 0 ]]; then
  first_node=${nodes[0]}
  join_ip=$(${etcdctl} get ${first_node})
  join_arg="--join ${join_ip}"
fi

${etcdctl} set /consul.io/bootstrap/machines/${this_machine} ${this_ip} > /dev/null

/bin/start --server --bootstrap-expect 3 --advertise ${this_ip} ${join_arg} $@
