#!/bin/bash

set -e

this_ip="$1"; shift
this_machine="$1"; shift
consul_args="$@"

etcdctl="docker run --net=host --rm cap10morgan/etcdctl:0.4.6"

${etcdctl} set /consul.io/bootstrap/machines/${this_machine} ${this_ip} > /dev/null

nodes=( $(${etcdctl} ls /consul.io/bootstrap/machines) )
first_node=${nodes[0]}

if [[ -n "${first_node}" ]]; then
  join_ip=$(${etcdctl} get ${first_node})
  if [[ "${join_ip}" == "${this_ip}" ]]; then
    join_arg=""
  else
    join_arg="--join ${join_ip}"
  fi
fi

ip_args="${this_ip}"

exec /bin/start --server --bootstrap-expect 3 --advertise ${this_ip} ${join_arg} $@
