#!/bin/bash

set -e

if [[ -z $DOCKER_REPO && -n $1 ]]; then
  DOCKER_REPO=$1
fi

if [[ -z $DOCKER_REPO ]]; then
  DOCKER_REPO=$(grep 'Environment=DOCKER_REPO=' consul@.service | awk -F\= '{print $3}')
fi

if [[ -z $DOCKER_REPO ]]; then
  echo 'Docker repo argument is required (or set the DOCKER_REPO env var).'
  exit 1
fi

echo '--- building docker image'
if [[ -z $BUILDBOX_BRANCH ]]; then
  BRANCH=$(git rev-parse --abbrev-ref HEAD)
else
  BRANCH=$BUILDBOX_BRANCH
fi

if [[ -z $BUILDBOX_COMMIT ]]; then
  COMMIT=HEAD
else
  COMMIT=$BUILDBOX_COMMIT
fi

export IMAGE_TAG=${BRANCH}-$(git rev-parse --short ${COMMIT})

echo 'Building ${DOCKER_REPO}:${IMAGE_TAG}'
docker build -t $DOCKER_REPO:$IMAGE_TAG .

if [[ $CI = "true" && $BUILDBOX_PULL_REQUEST = "false" ]]; then
  echo '--- pushing docker image to registry'
  docker push $DOCKER_REPO:$IMAGE_TAG
else
  echo "If you'd like to push this to the Docker repo, run: docker push ${DOCKER_REPO}:${IMAGE_TAG}"
fi

if hash buildbox-agent 2>/dev/null ; then
  buildbox-agent build-data set docker-image "${DOCKER_REPO}:${IMAGE_TAG}"
fi
